import uuid

import pytest
from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.engine import make_url

from app.database import Base

from .conftest import TEST_SERVER_URL, alembic_config


@pytest.fixture
def scratch_url():
    """An empty database, separate from the shared test database."""
    admin = create_engine(TEST_SERVER_URL, isolation_level="AUTOCOMMIT")
    name = f"shorts_migrate_{uuid.uuid4().hex[:12]}"
    with admin.connect() as conn:
        conn.execute(text(f'CREATE DATABASE "{name}"'))
    yield make_url(TEST_SERVER_URL).set(database=name).render_as_string(hide_password=False)
    with admin.connect() as conn:
        conn.execute(text(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))
    admin.dispose()


def current_revision(url):
    engine = create_engine(url)
    try:
        with engine.connect() as conn:
            return MigrationContext.configure(conn).get_current_revision()
    finally:
        engine.dispose()


def tables(url):
    engine = create_engine(url)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


def test_single_linear_history():
    script = ScriptDirectory.from_config(alembic_config(TEST_SERVER_URL))
    assert len(script.get_heads()) == 1
    revisions = list(script.walk_revisions())
    assert revisions[-1].down_revision is None


def test_upgrade_creates_schema(scratch_url):
    assert tables(scratch_url) == set()
    command.upgrade(alembic_config(scratch_url), "head")
    assert tables(scratch_url) == {"alembic_version", "videos"}
    assert current_revision(scratch_url) == "0001"


def test_upgrade_is_idempotent(scratch_url):
    config = alembic_config(scratch_url)
    command.upgrade(config, "head")
    command.upgrade(config, "head")
    assert current_revision(scratch_url) == "0001"


def test_downgrade_to_base_and_back(scratch_url):
    config = alembic_config(scratch_url)
    command.upgrade(config, "head")
    command.downgrade(config, "base")
    assert tables(scratch_url) == {"alembic_version"}
    assert current_revision(scratch_url) is None
    command.upgrade(config, "head")
    assert "videos" in tables(scratch_url)


def test_models_match_migrations(database_url):
    """Fails if a model changes without a matching migration."""
    engine = create_engine(database_url)
    try:
        with engine.connect() as conn:
            context = MigrationContext.configure(conn, opts={"compare_type": True})
            assert compare_metadata(context, Base.metadata) == []
    finally:
        engine.dispose()


def test_offline_sql_generation(capsys):
    command.upgrade(alembic_config(TEST_SERVER_URL), "head", sql=True)
    sql = capsys.readouterr().out
    assert "CREATE TABLE videos" in sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql


def test_env_falls_back_to_app_settings(monkeypatch, scratch_url):
    """`alembic upgrade head` without an explicit URL uses DATABASE_URL."""
    from alembic.config import Config

    from .conftest import BACKEND_DIR

    monkeypatch.setenv("DATABASE_URL", scratch_url.replace("postgresql+psycopg://", "postgresql://"))
    config = Config(str(BACKEND_DIR / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_DIR / "migrations"))
    config.attributes["configure_logger"] = False
    command.upgrade(config, "head")
    assert current_revision(scratch_url) == "0001"
